#!/bin/sh
set -e

# dir=/usr/src/php
dir=/usr/local/lib/php

usage() {
	echo "usage: $0 COMMAND"
	echo
	echo "Manage php source tarball lifecycle."
	echo
	echo "Commands:"
	echo "   extract  extract php source tarball into directory $dir if not already done."
	echo "   delete   delete extracted php source located into $dir if not already done."
	echo
}

case "$1" in
	extract)
		sudo mkdir -p "$dir"
		if [ ! -f "$dir/.docker-extracted" ]; then
      curl -fSL "https://github.com/php/php-src/archive/refs/tags/php-${PHP_VERSION}.tar.gz" > php.tar.gz && \
      sudo mv php.tar.gz /usr/local/lib && \
			sudo tar -xzf /usr/local/lib/php.tar.gz -C "$dir" --strip-components=1
			sudo touch "$dir/.docker-extracted"
		fi
		;;

	delete)
		sudo rm -rf "$dir"
		;;

	*)
		usage
		exit 1
		;;
esac